### ISSUE TITLE
U-Tree_Select模糊查询功能bug

### ISSUE THREAD

**Issue by Zhiyang666** [ueboot/ueboot#10]
![image](https://user-images.githubusercontent.com/37479399/46656899-a6201280-cbe1-11e8-9d13-7af16e33ab9e.png)

![image](https://user-images.githubusercontent.com/37479399/46656983-d962a180-cbe1-11e8-961a-63333e3ed2f8.png)
在输入框中输入节点名称后不能进行查询功能，获得不了子节点
葵哥赶紧改，不改没法活了

**Comment by yaakua** [comment]
已经解决，最新版本 1.7.13
