### ISSUE TITLE
在superFilter高级搜索中，结算月的onchange事件没有效果

### ISSUE THREAD

**Issue by Zhiyang666** [ueboot/ueboot#11]
![image](https://user-images.githubusercontent.com/37479399/46657131-2c3c5900-cbe2-11e8-874e-cd4f41d14d1f.png)
![image](https://user-images.githubusercontent.com/37479399/46657296-850bf180-cbe2-11e8-86be-b0158301a4d8.png)

![image](https://user-images.githubusercontent.com/37479399/46657311-8dfcc300-cbe2-11e8-810e-57e159739e4b.png)
在改变结算月时并不会调用此方法，因此在后台获取不了当前所选的时间，也就改变不了树形结构图

**Comment by yaakua** [comment]
已经解决 1.7.12
