### ISSUE TITLE
树结构节点选择BUG

### ISSUE THREAD

**Issue by yunfeiyao** [ueboot/ueboot#16]
![image](https://user-images.githubusercontent.com/43233555/47193887-c2f9da00-d387-11e8-9132-c1b51de3f4b0.png)
![image](https://user-images.githubusercontent.com/43233555/47193902-d2792300-d387-11e8-97b0-1378db2fd921.png)
![image](https://user-images.githubusercontent.com/43233555/47193910-d60caa00-d387-11e8-9e05-e51240934ef8.png)
![Uploading image.png…]()

**Comment by yunfeiyao** [comment]
![image](https://user-images.githubusercontent.com/43233555/47193937-ef155b00-d387-11e8-921c-a4dedd9a9b2a.png)

**Comment by yaakua** [comment]
1.7.31版本已经解决
