### ISSUE TITLE
自定RedisConfig，发现冲突，只好做了重构。是否有更方便的方式？

### ISSUE THREAD

**Issue by ZivHung** [ueboot/ueboot#24]

**Comment by yaakua** [comment]
![image](https://user-images.githubusercontent.com/1543846/77028156-0b7d5300-69d3-11ea-9c96-2c7eb06ab01f.png)
![image](https://user-images.githubusercontent.com/1543846/77028166-12a46100-69d3-11ea-9cc2-a80c59415218.png)
