### ISSUE TITLE
# 多级菜单展示

### ISSUE THREAD

**Issue by tuweiya** [ueboot/ueboot#3]
1. 在同时有二级菜单和三级菜单的情况下
    - 点击“带有三级菜单”的二级菜单，会展开此三级菜单，同时会管理其他“带有三级菜单”的二级菜单
   - 点击“没有三级菜单”的二级菜单，“带有三级菜单”的二级菜单不会自动合并
2. 当菜单长度一定时，会出现菜单名换行

![image](https://user-images.githubusercontent.com/26521358/45219870-d886d900-b2de-11e8-9ad6-15c9b512e71f.png)

**Comment by yaakua** [comment]
针对第1点：iview的默认Menu功能就是这样设置的，只对同级别的菜单做手风琴折叠。切换二级菜单，不会改变三级菜单状态。
针对第2点：框架增加了一个配置项，可以配置整体菜单的宽度(默认值是200px)
```
ueboot.Config.setConfig({
    axios:{baseURL: "", unauthorizedUrl: '/#/login'},
   //设置Main页面当中的菜单宽度
    page_main:{menuWidth:'220px'}
})

```

@tuweiya
